id = "odoo"
name = "Odoo"
version = "0.12.1"
schema_version = 1
authors = ["Odoo<help@odoo.com>"]
description = "This extension integrates the Odoo Language Server, that will help you in the development of your Odoo projects."
repository = "https://github.com/odoo/odoo-zed"

[language_servers.odoo]
name = "Odoo"
languages = ["Python", "HTML", "XML", "CSV"]

[language-servers.odoo.language_ids]
"Python" = "python"
"HTML" = "html"
"CSS" = "css"
"XML" = "xml"